-- 1. User Mock Data 삽입 (최우선 순위)

INSERT INTO users (user_id, email, password_hash, created_at)
VALUES (
           1,
           'kim.yejin.test@closetsaver.com',  -- ✅ 유효한 이메일 형식 사용
           '$2a$10$wTf/0P1B4s8s9H6a3vL5O.QjRkL5I8T3g4K7j6H5G9F2E7D4C3B2A', -- ✅ BCrypt 해시 값으로 대체 (길이 확보)
           NOW()
       );


-- 2. Clothes Mock Data 삽입 (user_id=1 참조)

INSERT INTO clothes (user_id, normalized_name, image_url, item_type, color_group, feature_neck, feature_sleeve, feature_pattern, fit_type, thickness, purchase_date, created_at) VALUES (1, '오버핏 그레이 후드 꽈배기 니트', 'https://github.com/dPwls0125/closet-saver-mock-images/blob/e056d320e5eeb71482f458a68f634fcb02dacf3d/images/sweater_grey_pattern.png?raw=true', 'KNIT', 'GREY', 'ROUND_NECK', 'LONG_SLEEVE', 'LOGO', 'OVERSIZE', 'THICK', '2023-09-12', NOW());
INSERT INTO clothes (user_id, normalized_name, image_url, item_type, color_group, feature_neck, feature_sleeve, feature_pattern, fit_type, thickness, purchase_date, created_at) VALUES (1, '화이트 브이넥 코튼 니트', 'https://github.com/dPwls0125/closet-saver-mock-images/blob/e056d320e5eeb71482f458a68f634fcb02dacf3d/images/sweater_white_plain.jpg?raw=true', 'KNIT', 'WHITE', 'V_NECK', 'LONG_SLEEVE', 'PLAIN', 'OVERSIZE', 'THICK', '2025-10-03', NOW());
INSERT INTO clothes (user_id, normalized_name, image_url, item_type, color_group, feature_neck, feature_sleeve, feature_pattern, fit_type, thickness, purchase_date, created_at) VALUES (1, '그레이 라운드넥 니트', 'https://github.com/dPwls0125/closet-saver-mock-images/blob/e056d320e5eeb71482f458a68f634fcb02dacf3d/images/T-shirt_grey_plain.jpg?raw=true', 'KNIT', 'GREY', 'ROUND_NECK', 'LONG_SLEEVE', 'PLAIN', 'OVERSIZE', 'MEDIUM', '2025-09-08', NOW());
INSERT INTO clothes (user_id, normalized_name, image_url, item_type, color_group, feature_neck, feature_sleeve, feature_pattern, fit_type, thickness, purchase_date, created_at) VALUES (1, '블랙 브이넥 슬림핏 시스루 니트', 'https://github.com/dPwls0125/closet-saver-mock-images/blob/e056d320e5eeb71482f458a68f634fcb02dacf3d/images/T-shirt_black_plain.jpg?raw=true', 'KNIT', 'BLACK', 'V_NECK', 'LONG_SLEEVE', 'PLAIN', 'SLIM_FIT', 'MEDIUM', '2025-09-17', NOW());
INSERT INTO clothes (user_id, normalized_name, image_url, item_type, color_group, feature_neck, feature_sleeve, feature_pattern, fit_type, thickness, purchase_date, created_at) VALUES (1, '블랙 무지 반팔', 'https://github.com/dPwls0125/closet-saver-mock-images/blob/e056d320e5eeb71482f458a68f634fcb02dacf3d/images/short_sleeved_T-shirt_black_plain.jpg?raw=true', 'T_SHIRT', 'BLACK', 'ROUND_NECK', 'SHORT_SLEEVE', 'PLAIN', 'OVERSIZE', 'THIN', '2025-09-10', NOW());
INSERT INTO clothes (user_id, normalized_name, image_url, item_type, color_group, feature_neck, feature_sleeve, feature_pattern, fit_type, thickness, purchase_date, created_at) VALUES (1, '흰색 무지 반팔', 'https://github.com/dPwls0125/closet-saver-mock-images/blob/e056d320e5eeb71482f458a68f634fcb02dacf3d/images/short_sleeved_T-shirt_white_plain.jpg?raw=true', 'T_SHIRT', 'WHITE', 'ROUND_NECK', 'SHORT_SLEEVE', 'PLAIN', 'OVERSIZE', 'THIN', '2025-05-06', NOW());
INSERT INTO clothes (user_id, normalized_name, image_url, item_type, color_group, feature_neck, feature_sleeve, feature_pattern, fit_type, thickness, purchase_date, created_at) VALUES (1, '블랙 슬림핏 반팔', 'https://github.com/dPwls0125/closet-saver-mock-images/blob/e056d320e5eeb71482f458a68f634fcb02dacf3d/images/short_sleeved_T-shirt_black_plain_crop.jpg?raw=true', 'T_SHIRT', 'BLACK', 'ROUND_NECK', 'LONG_SLEEVE', 'PLAIN', 'SLIM_FIT', 'THIN', '2025-03-05', NOW());
INSERT INTO clothes (user_id, normalized_name, image_url, item_type, color_group, feature_neck, feature_sleeve, feature_pattern, fit_type, thickness, purchase_date, created_at) VALUES (1, '앙고라 반팔 화이트 니트', 'https://github.com/dPwls0125/closet-saver-mock-images/blob/e056d320e5eeb71482f458a68f634fcb02dacf3d/images/short_sleeved_sweater_plain.jpg?raw=true', 'KNIT', 'WHITE', 'ROUND_NECK', 'LONG_SLEEVE', 'PLAIN', 'STANDARD', 'THICK', '2024-12-25', NOW());
INSERT INTO clothes (user_id, normalized_name, image_url, item_type, color_group, feature_neck, feature_sleeve, feature_pattern, fit_type, thickness, purchase_date, created_at) VALUES (1, '오버핏 언발 화이트 셔츠', 'https://github.com/dPwls0125/closet-saver-mock-images/blob/e056d320e5eeb71482f458a68f634fcb02dacf3d/images/shirt_white_plain_02.jpg?raw=true', 'SHIRT', 'WHITE', 'ROUND_NECK', 'LONG_SLEEVE', 'PLAIN', 'OVERSIZE', 'MEDIUM', '2025-10-29', NOW());
INSERT INTO clothes (user_id, normalized_name, image_url, item_type, color_group, feature_neck, feature_sleeve, feature_pattern, fit_type, thickness, purchase_date, created_at) VALUES (1, '오버핏 그레이 긴팔 셔츠', 'https://github.com/dPwls0125/closet-saver-mock-images/blob/e056d320e5eeb71482f458a68f634fcb02dacf3d/images/shirt_grey_plain.jpg?raw=true', 'SHIRT', 'GREY', 'ROUND_NECK', 'LONG_SLEEVE', 'PLAIN', 'OVERSIZE', 'MEDIUM', '2025-10-15', NOW());
INSERT INTO clothes (user_id, normalized_name, image_url, item_type, color_group, feature_neck, feature_sleeve, feature_pattern, fit_type, thickness, purchase_date, created_at) VALUES (1, '슬림핏 블랙 긴팔 셔츠', 'https://github.com/dPwls0125/closet-saver-mock-images/blob/e056d320e5eeb71482f458a68f634fcb02dacf3d/images/shirt_black_plain.jpg?raw=true', 'SHIRT', 'BLACK', 'ROUND_NECK', 'LONG_SLEEVE', 'PLAIN', 'SLIM_FIT', 'MEDIUM', '2025-10-07', NOW());
INSERT INTO clothes (user_id, normalized_name, image_url, item_type, color_group, feature_neck, feature_sleeve, feature_pattern, fit_type, thickness, purchase_date, created_at) VALUES (1, '오버핏 체크 그레이 긴팔 셔츠', 'https://github.com/dPwls0125/closet-saver-mock-images/blob/e056d320e5eeb71482f458a68f634fcb02dacf3d/images/shirt_grey_pattern.jpg?raw=true', 'SHIRT', 'GREY', 'ROUND_NECK', 'LONG_SLEEVE', 'LOGO', 'OVERSIZE', 'MEDIUM', '2025-04-22', NOW());
INSERT INTO clothes (user_id, normalized_name, image_url, item_type, color_group, feature_neck, feature_sleeve, feature_pattern, fit_type, thickness, purchase_date, created_at) VALUES (1, '슬림핏 크롭 화이트 셔츠', 'https://github.com/dPwls0125/closet-saver-mock-images/blob/e056d320e5eeb71482f458a68f634fcb02dacf3d/images/short_sleeved_shirt_logo.jpeg?raw=true', 'SHIRT', 'WHITE', 'ROUND_NECK', 'LONG_SLEEVE', 'PLAIN', 'STANDARD', 'MEDIUM', '2024-12-12', NOW());
INSERT INTO clothes (user_id, normalized_name, image_url, item_type, color_group, feature_neck, feature_sleeve, feature_pattern, fit_type, thickness, purchase_date, created_at) VALUES (1, '오버핏 그레이 젠지 반팔', 'https://github.com/dPwls0125/closet-saver-mock-images/blob/e056d320e5eeb71482f458a68f634fcb02dacf3d/images/short_sleeved_T-shirt_black_logo.jpg?raw=true', 'T_SHIRT', 'GREY', 'ROUND_NECK', 'SHORT_SLEEVE', 'PLAIN', 'OVERSIZE', 'THIN', '2025-04-16', NOW());
INSERT INTO clothes (user_id, normalized_name, image_url, item_type, color_group, feature_neck, feature_sleeve, feature_pattern, fit_type, thickness, purchase_date, created_at) VALUES (1, '오버핏 성격실패 로고 화이트 반팔', 'https://github.com/dPwls0125/closet-saver-mock-images/blob/e056d320e5eeb71482f458a68f634fcb02dacf3d/images/short_sleeved_T-shirt_logo.png?raw=true', 'T_SHIRT', 'WHITE', 'ROUND_NECK', 'SHORT_SLEEVE', 'LOGO', 'OVERSIZE', 'THIN', '2024-10-08', NOW());
INSERT INTO clothes (user_id, normalized_name, image_url, item_type, color_group, feature_neck, feature_sleeve, feature_pattern, fit_type, thickness, purchase_date, created_at) VALUES (1, '오버핏 무지 긴팔 화이트 티셔츠', 'https://github.com/dPwls0125/closet-saver-mock-images/blob/e056d320e5eeb71482f458a68f634fcb02dacf3d/images/T-shirt_white_plain.png?raw=true', 'T_SHIRT', 'WHITE', 'ROUND_NECK', 'LONG_SLEEVE', 'PLAIN', 'OVERSIZE', 'MEDIUM', '2025-05-07', NOW());
INSERT INTO clothes (user_id, normalized_name, image_url, item_type, color_group, feature_neck, feature_sleeve, feature_pattern, fit_type, thickness, purchase_date, created_at) VALUES (1, '슬림핏 화이트 셔츠', 'https://github.com/dPwls0125/closet-saver-mock-images/blob/e056d320e5eeb71482f458a68f634fcb02dacf3d/images/shirt_white_plain.jpg?raw=true', 'SHIRT', 'WHITE', 'ROUND_NECK', 'LONG_SLEEVE', 'PLAIN', 'SLIM_FIT', 'MEDIUM', '2025-10-27', NOW());
INSERT INTO clothes (user_id, normalized_name, image_url, item_type, color_group, feature_neck, feature_sleeve, feature_pattern, fit_type, thickness, purchase_date, created_at) VALUES (1, '슬림핏 크롭 반팔 셔츠', 'https://github.com/dPwls0125/closet-saver-mock-images/blob/e056d320e5eeb71482f458a68f634fcb02dacf3d/images/short_sleeved_shirt_logo.jpeg?raw=true', 'SHIRT', 'WHITE', 'ROUND_NECK', 'SHORT_SLEEVE', 'PLAIN', 'STANDARD', 'THIN', '2025-07-30', NOW());
INSERT INTO clothes (user_id, normalized_name, image_url, item_type, color_group, feature_neck, feature_sleeve, feature_pattern, fit_type, thickness, purchase_date, created_at) VALUES (1, '오버핏 로고 긴팔 화이트 티셔츠', 'https://github.com/dPwls0125/closet-saver-mock-images/blob/e056d320e5eeb71482f458a68f634fcb02dacf3d/images/T-shirt_white_logo.png?raw=true', 'T_SHIRT', 'WHITE', 'ROUND_NECK', 'LONG_SLEEVE', 'LOGO', 'OVERSIZE', 'MEDIUM', '2025-04-08', NOW());
INSERT INTO clothes (user_id, normalized_name, image_url, item_type, color_group, feature_neck, feature_sleeve, feature_pattern, fit_type, thickness, purchase_date, created_at) VALUES (1, '그레이 브이넥 울 니트', 'https://github.com/dPwls0125/closet-saver-mock-images/blob/e056d320e5eeb71482f458a68f634fcb02dacf3d/images/sweater_grey_plain.jpg?raw=true', 'KNIT', 'GREY', 'V_NECK', 'LONG_SLEEVE', 'PLAIN', 'OVERSIZE', 'THICK', '2025-10-01', NOW());
INSERT INTO clothes (user_id, normalized_name, image_url, item_type, color_group, feature_neck, feature_sleeve, feature_pattern, fit_type, thickness, purchase_date, created_at) VALUES (1, '슬림핏 화이트 니트', 'https://github.com/dPwls0125/closet-saver-mock-images/blob/e056d320e5eeb71482f458a68f634fcb02dacf3d/images/sweater_white_plain.png?raw=true', 'KNIT', 'WHITE', 'ROUND_NECK', 'LONG_SLEEVE', 'PLAIN', 'SLIM_FIT', 'THICK', '2024-11-20', NOW());





